---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by srokks.
--- DateTime: 10/01/2022 10:52
---
langAPI = RegisterMod("langAPI", 1)
include('langAPI_tables.lua')
include('langAPI.lua')
print('LangAPI successfully loaded')